{{- if .Values.service.tcpEnabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "safesurfer-powerdns.fullname" . }}-tcp
  labels:
    app: io.safesurfer.safesurfer-powerdns
  {{- if .Values.extraLabels }}
    {{- toYaml .Values.extraLabels | nindent 4 }}
  {{- end }}
    {{- include "safesurfer-powerdns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  externalIPs:
{{- if .Values.service.externalIPs }}
{{- with .Values.service.externalIPs }}
    {{- toYaml . | nindent 4 }}
{{- end }}
{{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5353
      protocol: TCP
      name: dns-tcp
  selector:
    app: io.safesurfer.safesurfer-powerdns
    {{- include "safesurfer-powerdns.selectorLabels" . | nindent 4 }}
{{- end }}
