#!/bin/bash -x

LOAD_BALANCER_IP="$(kubectl -n nginx-ingress get svc nginx-ingress-ingress-nginx-controller -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')"

kubectl get ns safesurfer-power-dev || kubectl create ns safesurfer-powerdns-dev

helm install safesurfer-powerdns \
  -n safesurfer-powerdns-dev \
  --set service.externalIPs[0]="$LOAD_BALANCER_IP" \
  --set service.type=LoadBalancer \
  --set service.externalTrafficPolicy=Local \
  deployments/safesurfer-powerdns
